# Generated by Django 3.2 on 2025-04-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
    ]
