# Generated by Django 3.2 on 2025-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_mail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ('-sent_at',), 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
        migrations.AddField(
            model_name='mail',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='Спам'),
        ),
    ]
